# Site settings
title: Sconsify
email: fabiofalci@gmail.com
description: >
  Your awesome Spotify service now in a client text mode
baseurl: ""
url: "https://fabiofalci.github.io/sconsify"
github_username: fabiofalci/sconsify

# Build settings
markdown: kramdown
